/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import common.MenuEnum;
import controller.Navigator;
import dto.MenuDto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import utils.ImageUtils;

/**
 *
 * @author PC
 */
public class FrMain extends javax.swing.JFrame {

    /**
     * Creates new form FrMain
     */
    public FrMain() {
        initComponents();
        this.setTitle("Student Tracking");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lbLogo.setIcon(new ImageIcon(getClass().getResource(ImageUtils.BKCIT_lOGO)));
        Navigator navigator= new Navigator(pnMenu);
        navigator.setStartPage();
        List<MenuDto> menus= new ArrayList<>();
        menus.add(new MenuDto(MenuEnum.HOMEPAGE, pnHomepage, lbHomePage));
        menus.add(new MenuDto(MenuEnum.COURSE_MANAGER, pnCourseMan, lbCourseMan));
        menus.add(new MenuDto(MenuEnum.STUDENT_MANAGER, pnStudentMan, lbStudentMan));
        navigator.setEvent(menus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        pnHomepage = new javax.swing.JPanel();
        lbHomePage = new javax.swing.JLabel();
        pnStudentMan = new javax.swing.JPanel();
        lbStudentMan = new javax.swing.JLabel();
        pnCourseMan = new javax.swing.JPanel();
        lbCourseMan = new javax.swing.JLabel();
        pnClass = new javax.swing.JPanel();
        lbClass = new javax.swing.JLabel();
        pnCourseMan2 = new javax.swing.JPanel();
        lbCourseMan2 = new javax.swing.JLabel();
        pnApp = new javax.swing.JPanel();
        lbApp = new javax.swing.JLabel();
        pnLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnLeft.setBackground(new java.awt.Color(0, 0, 0));
        pnLeft.setLayout(new java.awt.BorderLayout());

        pnMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 12));
        pnMenu.setLayout(new java.awt.GridLayout(8, 0, 0, 10));

        pnHomepage.setBackground(new java.awt.Color(96, 100, 191));
        pnHomepage.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbHomePage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbHomePage.setForeground(new java.awt.Color(255, 255, 255));
        lbHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu0_white_24dp.png"))); // NOI18N
        lbHomePage.setText("Màn Hình Chính");
        pnHomepage.add(lbHomePage);

        pnMenu.add(pnHomepage);

        pnStudentMan.setBackground(new java.awt.Color(0, 255, 51));
        pnStudentMan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbStudentMan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbStudentMan.setForeground(new java.awt.Color(255, 255, 255));
        lbStudentMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu1_white_24dp.png"))); // NOI18N
        lbStudentMan.setText("Quản Lý Học Viên");
        pnStudentMan.add(lbStudentMan);

        pnMenu.add(pnStudentMan);

        pnCourseMan.setBackground(new java.awt.Color(51, 255, 51));
        pnCourseMan.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbCourseMan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCourseMan.setForeground(new java.awt.Color(255, 255, 255));
        lbCourseMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu2_white_24dp.png"))); // NOI18N
        lbCourseMan.setText("Quản Lý Khóa Học");
        pnCourseMan.add(lbCourseMan);

        pnMenu.add(pnCourseMan);

        pnClass.setBackground(new java.awt.Color(51, 255, 51));
        pnClass.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbClass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbClass.setForeground(new java.awt.Color(255, 255, 255));
        lbClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu3_white_24dp.png"))); // NOI18N
        lbClass.setText("Quản Lý Lớp Học");
        pnClass.add(lbClass);

        pnMenu.add(pnClass);

        pnCourseMan2.setBackground(new java.awt.Color(51, 255, 51));
        pnCourseMan2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbCourseMan2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCourseMan2.setForeground(new java.awt.Color(255, 255, 255));
        lbCourseMan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu4_white_24dp.png"))); // NOI18N
        lbCourseMan2.setText("Thống kê dữ liệu");
        pnCourseMan2.add(lbCourseMan2);

        pnMenu.add(pnCourseMan2);

        pnLeft.add(pnMenu, java.awt.BorderLayout.CENTER);

        pnApp.setBackground(new java.awt.Color(255, 0, 0));
        pnApp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 20, 10));

        lbApp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbApp.setForeground(new java.awt.Color(255, 255, 255));
        lbApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_ung_dung_white_24dp.png"))); // NOI18N
        lbApp.setText("QUẢN LÝ HỌC VIÊN");
        lbApp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 10));
        pnApp.add(lbApp);

        pnLeft.add(pnApp, java.awt.BorderLayout.PAGE_START);

        pnLogo.setBackground(new java.awt.Color(0, 0, 0));
        pnLogo.add(lbLogo);

        pnLeft.add(pnLogo, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(pnLeft, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbApp;
    private javax.swing.JLabel lbClass;
    private javax.swing.JLabel lbCourseMan;
    private javax.swing.JLabel lbCourseMan2;
    private javax.swing.JLabel lbHomePage;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbStudentMan;
    private javax.swing.JPanel pnApp;
    private javax.swing.JPanel pnClass;
    private javax.swing.JPanel pnCourseMan;
    private javax.swing.JPanel pnCourseMan2;
    private javax.swing.JPanel pnHomepage;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnStudentMan;
    // End of variables declaration//GEN-END:variables
}
